//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Example.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        public static string NavSecurity {
            get {
                return ResourceManager.GetString("NavSecurity", resourceCulture);
            }
        }
        
        public static string NavAuth {
            get {
                return ResourceManager.GetString("NavAuth", resourceCulture);
            }
        }
        
        public static string HomeWelcome {
            get {
                return ResourceManager.GetString("HomeWelcome", resourceCulture);
            }
        }
        
        public static string FurtherInformation {
            get {
                return ResourceManager.GetString("FurtherInformation", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string AeroGear {
            get {
                return ResourceManager.GetString("AeroGear", resourceCulture);
            }
        }
        
        public static string NavCertPinning {
            get {
                return ResourceManager.GetString("NavCertPinning", resourceCulture);
            }
        }
        
        public static string NavDeviceProfileInfo {
            get {
                return ResourceManager.GetString("NavDeviceProfileInfo", resourceCulture);
            }
        }
        
        public static string NavDeviceTrust {
            get {
                return ResourceManager.GetString("NavDeviceTrust", resourceCulture);
            }
        }
        
        public static string NavDevReg {
            get {
                return ResourceManager.GetString("NavDevReg", resourceCulture);
            }
        }
        
        public static string NavDocumentation {
            get {
                return ResourceManager.GetString("NavDocumentation", resourceCulture);
            }
        }
        
        public static string NavIdtMgmt {
            get {
                return ResourceManager.GetString("NavIdtMgmt", resourceCulture);
            }
        }
        
        public static string NavMetrics {
            get {
                return ResourceManager.GetString("NavMetrics", resourceCulture);
            }
        }
        
        public static string NavPush {
            get {
                return ResourceManager.GetString("NavPush", resourceCulture);
            }
        }
        
        public static string NavPushMsg {
            get {
                return ResourceManager.GetString("NavPushMsg", resourceCulture);
            }
        }
        
        public static string NavSecStorage {
            get {
                return ResourceManager.GetString("NavSecStorage", resourceCulture);
            }
        }
        
        public static string NavTrustCheckInfo {
            get {
                return ResourceManager.GetString("NavTrustCheckInfo", resourceCulture);
            }
        }
        
        public static string NavDevSec {
            get {
                return ResourceManager.GetString("NavDevSec", resourceCulture);
            }
        }
        
        public static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        public static string NavSSO {
            get {
                return ResourceManager.GetString("NavSSO", resourceCulture);
            }
        }
        
        public static string UnderConstructionTitle {
            get {
                return ResourceManager.GetString("UnderConstructionTitle", resourceCulture);
            }
        }
        
        public static string button_close_caption {
            get {
                return ResourceManager.GetString("button.close.caption", resourceCulture);
            }
        }
        
        public static string button_showdocs_caption {
            get {
                return ResourceManager.GetString("button.showdocs.caption", resourceCulture);
            }
        }
        
        public static string dialog_notconfigured_title {
            get {
                return ResourceManager.GetString("dialog.notconfigured.title", resourceCulture);
            }
        }
        
        public static string dialog_notconfigured_message {
            get {
                return ResourceManager.GetString("dialog.notconfigured.message", resourceCulture);
            }
        }
        
        public static string service_auth_name {
            get {
                return ResourceManager.GetString("service.auth.name", resourceCulture);
            }
        }
        
        public static string idm_doc_link {
            get {
                return ResourceManager.GetString("idm.doc.link", resourceCulture);
            }
        }
        
        public static string idm_sso_doc_link {
            get {
                return ResourceManager.GetString("idm.sso.doc.link", resourceCulture);
            }
        }
        
        public static string device_security_doc_link {
            get {
                return ResourceManager.GetString("device.security.doc.link", resourceCulture);
            }
        }
        
        public static string push_doc_link {
            get {
                return ResourceManager.GetString("push.doc.link", resourceCulture);
            }
        }
        
        public static string metrics_doc_link {
            get {
                return ResourceManager.GetString("metrics.doc.link", resourceCulture);
            }
        }
        
        public static string auth_Login {
            get {
                return ResourceManager.GetString("auth.Login", resourceCulture);
            }
        }
        
        public static string auth_Logout {
            get {
                return ResourceManager.GetString("auth.Logout", resourceCulture);
            }
        }
        
        public static string auth_userDetails_FullName {
            get {
                return ResourceManager.GetString("auth.userDetails.FullName", resourceCulture);
            }
        }
        
        public static string auth_userDetails_Username {
            get {
                return ResourceManager.GetString("auth.userDetails.Username", resourceCulture);
            }
        }
        
        public static string auth_userDetails_Email {
            get {
                return ResourceManager.GetString("auth.userDetails.Email", resourceCulture);
            }
        }
        
        public static string auth_userDetails_AssignedRoles {
            get {
                return ResourceManager.GetString("auth.userDetails.AssignedRoles", resourceCulture);
            }
        }
        
        public static string auth_userDetails_Otp2FAEnabled {
            get {
                return ResourceManager.GetString("auth.userDetails.Otp2FAEnabled", resourceCulture);
            }
        }
        
        public static string auth_userDetails_EmailVerified {
            get {
                return ResourceManager.GetString("auth.userDetails.EmailVerified", resourceCulture);
            }
        }
        
        public static string DeviceSecurityDesc {
            get {
                return ResourceManager.GetString("DeviceSecurityDesc", resourceCulture);
            }
        }
        
        public static string IdtManagementDesc {
            get {
                return ResourceManager.GetString("IdtManagementDesc", resourceCulture);
            }
        }
        
        public static string MobileMetricsDesc {
            get {
                return ResourceManager.GetString("MobileMetricsDesc", resourceCulture);
            }
        }
        
        public static string PushNotificationsDesc {
            get {
                return ResourceManager.GetString("PushNotificationsDesc", resourceCulture);
            }
        }
    }
}
