//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Example.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AeroGear.
        /// </summary>
        public static string AeroGear {
            get {
                return ResourceManager.GetString("AeroGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AeroGear Xamarin Showcase.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string auth_Login {
            get {
                return ResourceManager.GetString("auth.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string auth_Logout {
            get {
                return ResourceManager.GetString("auth.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Roles.
        /// </summary>
        public static string auth_userDetails_AssignedRoles {
            get {
                return ResourceManager.GetString("auth.userDetails.AssignedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string auth_userDetails_Email {
            get {
                return ResourceManager.GetString("auth.userDetails.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verified.
        /// </summary>
        public static string auth_userDetails_EmailVerified {
            get {
                return ResourceManager.GetString("auth.userDetails.EmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string auth_userDetails_FullName {
            get {
                return ResourceManager.GetString("auth.userDetails.FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP 2FA Enabled.
        /// </summary>
        public static string auth_userDetails_Otp2FAEnabled {
            get {
                return ResourceManager.GetString("auth.userDetails.Otp2FAEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string auth_userDetails_Username {
            get {
                return ResourceManager.GetString("auth.userDetails.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string button_close_caption {
            get {
                return ResourceManager.GetString("button.close.caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Documentation.
        /// </summary>
        public static string button_showdocs_caption {
            get {
                return ResourceManager.GetString("button.showdocs.caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.aerogear.org/aerogear/latest/security/index.html.
        /// </summary>
        public static string device_security_doc_link {
            get {
                return ResourceManager.GetString("device.security.doc.link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Device Security service allows you to easily configure and manage device security, and trust checks for your mobile app.
        ///&lt;br/&gt;&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Perform a range of device trust checks on the mobile device, such as checking if the device is rooted, and allows you take proactive action based on the results&lt;/li&gt;
        ///&lt;li&gt;Distribute SSL certificates with a mobile app to create a direct chain of trust (certificate pinning)&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;br&gt;.
        /// </summary>
        public static string DeviceSecurityDesc {
            get {
                return ResourceManager.GetString("DeviceSecurityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string dialog_error_title {
            get {
                return ResourceManager.GetString("dialog.error.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} does not have a configuration in mobile-services.json. Refer to the documentation for instructions on how to configure this service..
        /// </summary>
        public static string dialog_notconfigured_message {
            get {
                return ResourceManager.GetString("dialog.notconfigured.message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Not Configured.
        /// </summary>
        public static string dialog_notconfigured_title {
            get {
                return ResourceManager.GetString("dialog.notconfigured.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             &lt;center&gt;For further information, visit &lt;span style=&quot;color: #2e6980&quot;&gt;&lt;a href=&quot;http://www.aerogear.org&quot; &gt;www.aerogear.org&lt;/a&gt;&lt;/span&gt;&lt;/center&gt;
        ///    .
        /// </summary>
        public static string FurtherInformation {
            get {
                return ResourceManager.GetString("FurtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;center&gt;This app demonstrates how to use the AeroGear Mobile services, backed by OpenShift to perform a wide range of common mobile tasks such as Identity Management, Device Security, Metrics Capture, Push Notifications and more.&lt;/center&gt;
        ///    &lt;br&gt;
        ///    .
        /// </summary>
        public static string HomeWelcome {
            get {
                return ResourceManager.GetString("HomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.aerogear.org/aerogear/latest/keycloak/index.html.
        /// </summary>
        public static string idm_doc_link {
            get {
                return ResourceManager.GetString("idm.doc.link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.aerogear.org/aerogear/latest/keycloak/index.html?sso=1.
        /// </summary>
        public static string idm_sso_doc_link {
            get {
                return ResourceManager.GetString("idm.sso.doc.link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Identity Management service allows you to add authentication and authorization to your mobile app.
        ///&lt;br/&gt;&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Secure your mobile app using the industry standard OpenID Connect protocol&lt;/li&gt;
        ///&lt;li&gt;Add access control to your app based on user’s group membership&lt;/li&gt;
        ///&lt;li&gt;Easily implement SSO, multi factor authentication and Social Login support&lt;/li&gt;
        ///&lt;li&gt;Back end support for identity brokering and user federation&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;br&gt;.
        /// </summary>
        public static string IdtManagementDesc {
            get {
                return ResourceManager.GetString("IdtManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.aerogear.org/aerogear/latest/metrics/index.html.
        /// </summary>
        public static string metrics_doc_link {
            get {
                return ResourceManager.GetString("metrics.doc.link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mobile Metrics service allows you gather metrics on mobile apps, device versions, device security checks and back-end mobile service usage.
        ///&lt;br/&gt;&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Monitor usage by version of mobile app, platform and SDK&lt;/li&gt;
        ///&lt;li&gt;Monitor interactions with the Identity Management service&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;br&gt;.
        /// </summary>
        public static string MobileMetricsDesc {
            get {
                return ResourceManager.GetString("MobileMetricsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string NavAuth {
            get {
                return ResourceManager.GetString("NavAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cert Pinning.
        /// </summary>
        public static string NavCertPinning {
            get {
                return ResourceManager.GetString("NavCertPinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Profile Info.
        /// </summary>
        public static string NavDeviceProfileInfo {
            get {
                return ResourceManager.GetString("NavDeviceProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Trust.
        /// </summary>
        public static string NavDeviceTrust {
            get {
                return ResourceManager.GetString("NavDeviceTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Registration.
        /// </summary>
        public static string NavDevReg {
            get {
                return ResourceManager.GetString("NavDevReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Security.
        /// </summary>
        public static string NavDevSec {
            get {
                return ResourceManager.GetString("NavDevSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string NavDocumentation {
            get {
                return ResourceManager.GetString("NavDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Management.
        /// </summary>
        public static string NavIdtMgmt {
            get {
                return ResourceManager.GetString("NavIdtMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string NavMetrics {
            get {
                return ResourceManager.GetString("NavMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notifications.
        /// </summary>
        public static string NavPush {
            get {
                return ResourceManager.GetString("NavPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Messages.
        /// </summary>
        public static string NavPushMsg {
            get {
                return ResourceManager.GetString("NavPushMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Storage.
        /// </summary>
        public static string NavSecStorage {
            get {
                return ResourceManager.GetString("NavSecStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string NavSecurity {
            get {
                return ResourceManager.GetString("NavSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSO.
        /// </summary>
        public static string NavSSO {
            get {
                return ResourceManager.GetString("NavSSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aerogear.org.
        /// </summary>
        public static string NavSubheader {
            get {
                return ResourceManager.GetString("NavSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Check Info.
        /// </summary>
        public static string NavTrustCheckInfo {
            get {
                return ResourceManager.GetString("NavTrustCheckInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.aerogear.org/aerogear/latest/push/index.html.
        /// </summary>
        public static string push_doc_link {
            get {
                return ResourceManager.GetString("push.doc.link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Push Notifications service allows you send native push notifications to different mobile operating systems.
        ///&lt;br/&gt;&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Code once and send push notifications to iOS and Android&lt;/li&gt;
        ///&lt;li&gt;Push notifications to defined groups&lt;/li&gt;
        ///&lt;li&gt;Push notifications to either iOS only or Android only&lt;/li&gt;
        ///&lt;li&gt;Push notifications to different variants of a mobile app&lt;/li&gt;
        ///&lt;li&gt;Push notifications from different back-end apps to the same mobile app&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;br&gt;            
        ///.
        /// </summary>
        public static string PushNotificationsDesc {
            get {
                return ResourceManager.GetString("PushNotificationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed.
        /// </summary>
        public static string service_auth_authentication_failed {
            get {
                return ResourceManager.GetString("service.auth.authentication.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identity management.
        /// </summary>
        public static string service_auth_name {
            get {
                return ResourceManager.GetString("service.auth.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;center&gt;This feature is currently under construction for this platform.
        ///&lt;br&gt;&lt;br&gt;
        ///If you would like to get involved in this work, please check out our community contribution page.&lt;br&gt;&lt;span style=&quot;color: #2e6980&quot;&gt;
        /// &lt;br&gt;&lt;a href=&quot;http://www.aerogear.org/community#guides&quot;&gt;www.aerogear.org/community#guides&lt;/a&gt;&lt;/span&gt;&lt;/center&gt;
        ///    .
        /// </summary>
        public static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Construction.
        /// </summary>
        public static string UnderConstructionTitle {
            get {
                return ResourceManager.GetString("UnderConstructionTitle", resourceCulture);
            }
        }
    }
}
