//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.iOS.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecurityResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Example.iOS.Resources.SecurityResources", typeof(SecurityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string device_lock_detected {
            get {
                return ResourceManager.GetString("device.lock.detected", resourceCulture);
            }
        }
        
        internal static string device_lock_not_detected {
            get {
                return ResourceManager.GetString("device.lock.not.detected", resourceCulture);
            }
        }
        
        internal static string device_debugger_detected {
            get {
                return ResourceManager.GetString("device.debugger.detected", resourceCulture);
            }
        }
        
        internal static string device_debugger_not_detected {
            get {
                return ResourceManager.GetString("device.debugger.not.detected", resourceCulture);
            }
        }
        
        internal static string device_jailbreak_detected {
            get {
                return ResourceManager.GetString("device.jailbreak.detected", resourceCulture);
            }
        }
        
        internal static string device_jailbreak_not_detected {
            get {
                return ResourceManager.GetString("device.jailbreak.not.detected", resourceCulture);
            }
        }
        
        internal static string device_emulator_detected {
            get {
                return ResourceManager.GetString("device.emulator.detected", resourceCulture);
            }
        }
        
        internal static string device_emulator_not_detected {
            get {
                return ResourceManager.GetString("device.emulator.not.detected", resourceCulture);
            }
        }
    }
}
